/* Third-party generated code: copied from intelli-piano `inc/midiseq2/midiseq2.jison.js`, which
   jison builds from `midiseq2.jison`. Do not hand-edit the parser tables; re-copy from that repo
   when the grammar changes. Only the module tail at the bottom of this file is adapted (CommonJS ->
   ESM) so it can be bundled for the browser. */
/* eslint-disable */
/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var parser = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,5],$V1=[1,6],$V2=[1,7],$V3=[1,8],$V4=[5,7,8,10,11],$V5=[1,12],$V6=[1,13],$V7=[1,25],$V8=[1,20],$V9=[1,21],$Va=[1,22],$Vb=[1,23],$Vc=[1,28],$Vd=[5,7,8,10,11,14,18,19,20,23],$Ve=[5,7,8,10,11,21],$Vf=[1,30],$Vg=[5,7,8,10,11,14,21];
var parser = {trace: function trace () { },
yy: {},
symbols_: {"error":2,"file":3,"statements":4,"EOF":5,"statement":6,"ELAPSE":7,"AT_MEASURE":8,"decimal":9,"AT_TICK":10,"KEYWORD":11,"args":12,"INT":13,"NIBBLE":14,"prefixes":15,"fields":16,"prefix":17,"CHANNEL":18,"HASH":19,"DOLLAR":20,"UNDERSCORE":21,"wide":22,"MINUS":23,"nibbles":24,"$accept":0,"$end":1},
terminals_: {2:"error",5:"EOF",7:"ELAPSE",8:"AT_MEASURE",10:"AT_TICK",11:"KEYWORD",13:"INT",14:"NIBBLE",18:"CHANNEL",19:"HASH",20:"DOLLAR",21:"UNDERSCORE",23:"MINUS"},
productions_: [0,[3,2],[3,1],[4,2],[4,1],[6,1],[6,2],[6,2],[6,2],[6,1],[9,1],[9,1],[12,2],[12,1],[12,1],[15,2],[15,1],[17,1],[17,1],[17,1],[16,3],[16,1],[22,2],[22,1],[24,2],[24,1]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1: case 2:
 return builderOf(yy).finish(); 
break;
case 5:
 builderOf(yy).addElapse($$[$0]); 
break;
case 6:
 builderOf(yy).setMeasure($$[$0]); 
break;
case 7:
 builderOf(yy).setTick($$[$0]); 
break;
case 8:
 dispatch(builderOf(yy), $$[$0-1], $$[$0], yylineno + 1); 
break;
case 9:
 dispatch(builderOf(yy), $$[$0], emptyArgs(), yylineno + 1); 
break;
case 10: case 11: case 13:
 this.$ = $$[$0]; 
break;
case 12:
 this.$ = withFields($$[$0-1], $$[$0]); 
break;
case 14:
 this.$ = withFields(emptyArgs(), $$[$0]); 
break;
case 15:
 this.$ = mergeArg($$[$0-1], $$[$0]); 
break;
case 16:
 this.$ = mergeArg(emptyArgs(), $$[$0]); 
break;
case 17:
 this.$ = {kind: "channel", value: $$[$0]}; 
break;
case 18:
 this.$ = {kind: "hash", value: $$[$0]}; 
break;
case 19:
 this.$ = {kind: "dollar", value: $$[$0]}; 
break;
case 20:
 $$[$0-2].push($$[$0]); this.$ = $$[$0-2]; 
break;
case 21: case 25:
 this.$ = [$$[$0]]; 
break;
case 22:
 this.$ = wideValue(true, $$[$0]); 
break;
case 23:
 this.$ = wideValue(false, $$[$0]); 
break;
case 24:
 $$[$0-1].push($$[$0]); this.$ = $$[$0-1]; 
break;
}
},
table: [{3:1,4:2,5:[1,3],6:4,7:$V0,8:$V1,10:$V2,11:$V3},{1:[3]},{5:[1,9],6:10,7:$V0,8:$V1,10:$V2,11:$V3},{1:[2,2]},o($V4,[2,4]),o($V4,[2,5]),{9:11,13:$V5,14:$V6},{9:14,13:$V5,14:$V6},o($V4,[2,9],{12:15,15:16,16:17,17:18,22:19,24:24,14:$V7,18:$V8,19:$V9,20:$Va,23:$Vb}),{1:[2,1]},o($V4,[2,3]),o($V4,[2,6]),o($V4,[2,10]),o($V4,[2,11]),o($V4,[2,7]),o($V4,[2,8]),o($V4,[2,13],{22:19,24:24,16:26,17:27,14:$V7,18:$V8,19:$V9,20:$Va,23:$Vb}),o($V4,[2,14],{21:$Vc}),o($Vd,[2,16]),o($Ve,[2,21]),o($Vd,[2,17]),o($Vd,[2,18]),o($Vd,[2,19]),{14:$V7,24:29},o($Ve,[2,23],{14:$Vf}),o($Vg,[2,25]),o($V4,[2,12],{21:$Vc}),o($Vd,[2,15]),{14:$V7,22:31,23:$Vb,24:24},o($Ve,[2,22],{14:$Vf}),o($Vg,[2,24]),o($Ve,[2,20])],
defaultActions: {3:[2,2],9:[2,1]},
parseError: function parseError (str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        var error = new Error(str);
        error.hash = hash;
        throw error;
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        var lex = function () {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        };
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};

	const NIBBLE = "0123456789abcdef";

	// A wide field is a nibble run, MSB first, with an optional leading "-".
	const wideValue = (negative, nibbles) => {
		let value = 0;
		for (const n of nibbles)
			value = value * 16 + n;
		return negative ? -value : value;
	};

	// mido-style keyword -> the music-widgets event shape. `args` is the parsed argument bundle:
	// {channel, hash, dollar, fields} where `fields` is the list of wide values (split on `_`).
	const buildEvent = (keyword, args, line) => {
		const need = (count) => {
			if (args.fields.length < count)
				throw new Error(`midiseq2: ${keyword} needs ${count} field(s), got ${args.fields.length} (line ${line})`);
		};
		// An absent byte token means 0, per the format's zero-elision rule.
		const byteOr0 = (token) => token === null ? 0 : token;
		// A meta event carries no channel; rejecting it here catches a malformed line rather than
		// silently dropping the token.
		const noChannel = () => {
			if (args.channel !== null)
				throw new Error(`midiseq2: ${keyword} is a meta event and takes no channel (line ${line})`);
		};
		const event = {type: "channel", subtype: keyword, channel: args.channel === null ? 0 : args.channel};

		switch (keyword) {
		case "set_tempo":
			noChannel(); need(1);
			return Object.assign(event, {type: "meta", subtype: "setTempo", microsecondsPerBeat: args.fields[0]});
		case "time_signature":
			noChannel(); need(4);
			return Object.assign(event, {type: "meta", subtype: "timeSignature",
				numerator: args.fields[0], denominator: args.fields[1],
				metronome: args.fields[2], thirtyseconds: args.fields[3]});
		case "key_signature":
			noChannel(); need(2);
			return Object.assign(event, {type: "meta", subtype: "keySignature", key: args.fields[0], scale: args.fields[1]});
		case "sequence_number":
			noChannel(); need(1);
			return Object.assign(event, {type: "meta", subtype: "sequenceNumber", number: args.fields[0]});
		case "channel_prefix":
			noChannel(); need(1);
			// the prefix's payload IS a channel, but it arrives as a wide field, not a C token.
			return Object.assign(event, {type: "meta", subtype: "midiChannelPrefix", channel: args.fields[0]});
		case "smpte_offset":
			noChannel(); need(6);
			return Object.assign(event, {type: "meta", subtype: "smpteOffset",
				frameRate: args.fields[0], hour: args.fields[1], min: args.fields[2],
				sec: args.fields[3], frame: args.fields[4], subframe: args.fields[5]});
		case "end_of_track":
			noChannel();
			return Object.assign(event, {type: "meta", subtype: "endOfTrack"});
		// Channel events. music-widgets names these after the MIDI wire spec while midiseq2 uses the
		// mido names, so the subtype is translated here; the serializer accepts both spellings.
		// Every byte token is OPTIONAL and defaults to 0: the format elides a zero-valued token, so
		// `program_change` (program 0) and `note_on #3c` (velocity 0) are both well-formed. Demanding
		// the token here rejected 143 real `program_change` lines.
		case "note_on":
			return Object.assign(event, {subtype: "noteOn", noteNumber: byteOr0(args.hash), velocity: byteOr0(args.dollar)});
		case "note_off":
			return Object.assign(event, {subtype: "noteOff", noteNumber: byteOr0(args.hash), velocity: byteOr0(args.dollar)});
		case "polytouch":
			return Object.assign(event, {subtype: "noteAftertouch", noteNumber: byteOr0(args.hash), amount: byteOr0(args.dollar)});
		case "control_change":
			return Object.assign(event, {subtype: "controller", controllerType: byteOr0(args.hash), value: byteOr0(args.dollar)});
		case "program_change":
			return Object.assign(event, {subtype: "programChange", programNumber: byteOr0(args.hash)});
		case "aftertouch":
			return Object.assign(event, {subtype: "channelAftertouch", amount: byteOr0(args.hash)});
		case "pitchwheel":
			// a pitchwheel at centre (0) elides its field too.
			return Object.assign(event, {subtype: "pitchBend", value: args.fields.length ? args.fields[0] : 0});
		default:
			throw new Error(`midiseq2: unknown event \`${keyword}\` (line ${line})`);
		}
	};

	const emptyArgs = () => ({channel: null, hash: null, dollar: null, fields: []});

	const withFields = (args, fields) => { args.fields = fields; return args; };

	// Fold one argument into the bundle. A `_` only separates fields, so it carries no value; a
	// repeated channel/#/$ is a malformed line rather than a last-one-wins.
	const mergeArg = (args, arg) => {
		switch (arg.kind) {
		case "channel":
			if (args.channel !== null)
				throw new Error("midiseq2: duplicate channel token");
			args.channel = arg.value;
			break;
		case "hash":
			if (args.hash !== null)
				throw new Error("midiseq2: duplicate #xx token");
			args.hash = arg.value;
			break;
		case "dollar":
			if (args.dollar !== null)
				throw new Error("midiseq2: duplicate $xx token");
			args.dollar = arg.value;
			break;
		case "field":
			args.fields.push(arg.value);
			break;
		case "separator":
			break;
		}
		return args;
	};

	// Accumulates statements into a MidiData. Held on the parser instance so a parse is reentrant.
	class Builder {
		constructor () {
			this.header = {formatType: 1, trackCount: 1, ticksPerBeat: 480};
			this.events = [];
			this.elapsed = 0;
			this.measureIndex = undefined;
			this.tickInMeasure = undefined;
		}

		setHeader (name, value) {
			if (name === "ticks_per_beat")
				this.header.ticksPerBeat = value;
			else
				this.header.formatType = value;
		}

		addElapse (value) { this.elapsed += value; }

		// `@measure` persists across events; `@tick` is consumed by the next event alone.
		setMeasure (index) { this.measureIndex = index; }
		setTick (tick) { this.tickInMeasure = tick; }

		addEvent (event) {
			event.deltaTime = this.elapsed;
			this.elapsed = 0;
			if (this.measureIndex !== undefined)
				event.measureIndex = this.measureIndex;
			if (this.tickInMeasure !== undefined)
				event.tickInMeasure = this.tickInMeasure;
			this.tickInMeasure = undefined;
			this.events.push(event);
		}

		finish () {
			// A file may end without an explicit end_of_track; MIDI requires one, and any trailing
			// elapse time belongs to it.
			if (!this.events.some(e => e.subtype === "endOfTrack"))
				this.events.push({deltaTime: this.elapsed, type: "meta", subtype: "endOfTrack"});
			return {header: this.header, tracks: [this.events]};
		}
	}

	// One builder per parse, created on first use and read back by the `file` rule.
	const builderOf = (yy) => yy.builder || (yy.builder = new Builder());

	const HEADERS = new Set(["ticks_per_beat", "format_type"]);

	// `KEYWORD args` covers both headers and events (they are the same shape), so split them here.
	const dispatch = (builder, keyword, args, line) => {
		if (HEADERS.has(keyword)) {
			if (args.fields.length !== 1)
				throw new Error(`midiseq2: ${keyword} needs exactly one value (line ${line})`);
			if (args.channel !== null || args.hash !== null || args.dollar !== null)
				throw new Error(`midiseq2: ${keyword} takes no channel or byte token (line ${line})`);
			builder.setHeader(keyword, args.fields[0]);
			return;
		}
		builder.addEvent(buildEvent(keyword, args, line));
	};
/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function(match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex () {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin (condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState () {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules () {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState (n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState (condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {"flex":true},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:/* skip: whitespace separates tokens but carries no meaning */
break;
case 1:return 8;
break;
case 2:return 10;
break;
case 3:yy_.yytext = parseInt(yy_.yytext.slice(1), 16); return 7;
break;
case 4:yy_.yytext = parseInt(yy_.yytext.slice(1), 16); return 18;
break;
case 5:yy_.yytext = parseInt(yy_.yytext.slice(1), 16); return 19;
break;
case 6:yy_.yytext = parseInt(yy_.yytext.slice(1), 16); return 20;
break;
case 7:return 21;
break;
case 8:return 23;
break;
case 9:yy_.yytext = NIBBLE.indexOf(yy_.yytext.toLowerCase()); return 14;
break;
case 10:yy_.yytext = parseInt(yy_.yytext, 10); return 13;
break;
case 11:return 11;
break;
case 12:return 5;
break;
case 13: throw new Error(`midiseq2: unexpected character \`${yy_.yytext}\` at line ${yy_.yylineno + 1}`); 
break;
case 14:console.log(yy_.yytext);
break;
}
},
rules: [/^(?:[ \t\r\n]+)/,/^(?:@measure)/,/^(?:@tick)/,/^(?:E[0-9a-fA-F]+)/,/^(?:C[0-9a-fA-F])/,/^(?:#[0-9a-fA-F]{2})/,/^(?:\$[0-9a-fA-F]{2})/,/^(?:_)/,/^(?:-)/,/^(?:[0-9a-fA-F])/,/^(?:[0-9]+)/,/^(?:[a-z_][a-z0-9_]*)/,/^(?:$)/,/^(?:.)/,/^(?:.)/],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


/* Adapted for the browser bundle: jison's generated CommonJS tail (exports.* plus a
   `require('fs')` CLI main) is replaced by an ESM export, so Vite neither has to interop a CJS
   module nor resolve node builtins. Nothing above this line is modified. */
export const parse = function () { return parser.parse.apply(parser, arguments); };
export {parser};
export default {parse, parser};
