application: klstudioindieg
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py

- url: /MessageBoard
  script: main.py

- url: /MessageBoard/.*
  script: main.py

- url: /html/.*
  script: main.py


- url: /tanx-web-service/v1/static/
  static_dir: TanxWebService/static

- url: /tanx-web-service/v1/admin/.*
  script: TanxWebService/admin.py
  login: admin

- url: /tanx-web-service/v1/.*
  script: TanxWebService/main.py
  login: required


- url: /
  static_dir: static
